spring:
  datasource:
    username: 'sa'
    password: 'sa'
    url: 'jdbc:h2:mem:test'
    driver-class-name: org.h2.Driver

graphql:
  servlet:
    mapping: '/graphql'
    enabled: true
    corsEnabled: true

graphiql:
  enabled: true
  endpoint: '/graphql'
  mapping: '/graphiql'
